# memory
shared_buffers = 4GB
effective_cache_size = 12GB
work_mem = 128MB
maintenance_work_mem = 1GB
wal_buffers = -1
min_wal_size = 1GB
max_wal_size = 4GB
checkpoint_completion_target = 0.9

# WAL
wal_compression = lz4

# planner/statistics
default_statistics_target = 500
random_page_cost = 1.1
effective_io_concurrency = 256
jit = off

# parallelism (8 vCPU / AMD EPYC 9645)
max_worker_processes = 16
max_parallel_workers = 8
max_parallel_workers_per_gather = 4
max_parallel_maintenance_workers = 4
io_method = worker

autovacuum_max_workers = 4
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
autovacuum_vacuum_cost_delay = 2ms
autovacuum_vacuum_cost_limit = 400

# connections (using pgbouncer so only ~60 connections)
max_connections = 60
listen_addresses = '*'
