packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  "@bufbuild/buf": true
  "@swc/core": true
  bufferutil: true
  core-js: true
  esbuild: true
  exifreader: true
  msw: true
  protobufjs: true
  sharp: true
  zlib-sync: true

settings:
  minimumReleaseAge: 1440
