/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareTargetRouteImport } from './routes/share-target'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTosRouteImport } from './routes/_layout/tos'
import { Route as LayoutSubmissionRouteImport } from './routes/_layout/submission'
import { Route as LayoutStatisticsRouteImport } from './routes/_layout/statistics'
import { Route as LayoutStationsRouteImport } from './routes/_layout/stations'
import { Route as LayoutPreferencesRouteImport } from './routes/_layout/preferences'
import { Route as LayoutListsRouteImport } from './routes/_layout/lists'
import { Route as LayoutDeletedEntriesRouteImport } from './routes/_layout/deleted-entries'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutClfExportRouteImport } from './routes/_layout/clf-export'
import { Route as LayoutChangelogRouteImport } from './routes/_layout/changelog'
import { Route as LayoutAnalyzerRouteImport } from './routes/_layout/analyzer'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutListsIndexRouteImport } from './routes/_layout/lists/index'
import { Route as LayoutListsUuidRouteImport } from './routes/_layout/lists/$uuid'
import { Route as LayoutAdminLayoutRouteImport } from './routes/_layout/admin/_layout'
import { Route as LayoutAccountTwoFactorRouteImport } from './routes/_layout/account/two-factor'
import { Route as LayoutAccountSubmissionsRouteImport } from './routes/_layout/account/submissions'
import { Route as LayoutAccountSettingsRouteImport } from './routes/_layout/account/settings'
import { Route as LayoutAccountResetPasswordRouteImport } from './routes/_layout/account/reset-password'
import { Route as LayoutAdminLayoutUkePermitsRouteImport } from './routes/_layout/admin/_layout/uke-permits'
import { Route as LayoutAdminLayoutUkeImportRouteImport } from './routes/_layout/admin/_layout/uke-import'
import { Route as LayoutAdminLayoutSettingsRouteImport } from './routes/_layout/admin/_layout/settings'
import { Route as LayoutAdminLayoutAuditLogsRouteImport } from './routes/_layout/admin/_layout/audit-logs'
import { Route as LayoutAdminLayoutUsersIndexRouteImport } from './routes/_layout/admin/_layout/users/index'
import { Route as LayoutAdminLayoutSubmissionsIndexRouteImport } from './routes/_layout/admin/_layout/submissions/index'
import { Route as LayoutAdminLayoutStationsIndexRouteImport } from './routes/_layout/admin/_layout/stations/index'
import { Route as LayoutAdminLayoutLocationsIndexRouteImport } from './routes/_layout/admin/_layout/locations/index'
import { Route as LayoutAdminLayoutListsIndexRouteImport } from './routes/_layout/admin/_layout/lists/index'
import { Route as LayoutAdminLayoutCommentsIndexRouteImport } from './routes/_layout/admin/_layout/comments/index'
import { Route as LayoutAdminLayoutUsersIdRouteImport } from './routes/_layout/admin/_layout/users/$id'
import { Route as LayoutAdminLayoutSubmissionsIdRouteImport } from './routes/_layout/admin/_layout/submissions/$id'
import { Route as LayoutAdminLayoutStationsIdRouteImport } from './routes/_layout/admin/_layout/stations/$id'
import { Route as LayoutAdminLayoutLocationsIdRouteImport } from './routes/_layout/admin/_layout/locations/$id'

const ShareTargetRoute = ShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTosRoute = LayoutTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubmissionRoute = LayoutSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStatisticsRoute = LayoutStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStationsRoute = LayoutStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPreferencesRoute = LayoutPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutListsRoute = LayoutListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeletedEntriesRoute = LayoutDeletedEntriesRouteImport.update({
  id: '/deleted-entries',
  path: '/deleted-entries',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClfExportRoute = LayoutClfExportRouteImport.update({
  id: '/clf-export',
  path: '/clf-export',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChangelogRoute = LayoutChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyzerRoute = LayoutAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutListsIndexRoute = LayoutListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutListsRoute,
} as any)
const LayoutListsUuidRoute = LayoutListsUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => LayoutListsRoute,
} as any)
const LayoutAdminLayoutRoute = LayoutAdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountTwoFactorRoute = LayoutAccountTwoFactorRouteImport.update({
  id: '/account/two-factor',
  path: '/account/two-factor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountSubmissionsRoute =
  LayoutAccountSubmissionsRouteImport.update({
    id: '/account/submissions',
    path: '/account/submissions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccountSettingsRoute = LayoutAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountResetPasswordRoute =
  LayoutAccountResetPasswordRouteImport.update({
    id: '/account/reset-password',
    path: '/account/reset-password',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminLayoutUkePermitsRoute =
  LayoutAdminLayoutUkePermitsRouteImport.update({
    id: '/uke-permits',
    path: '/uke-permits',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutUkeImportRoute =
  LayoutAdminLayoutUkeImportRouteImport.update({
    id: '/uke-import',
    path: '/uke-import',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutSettingsRoute =
  LayoutAdminLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutAuditLogsRoute =
  LayoutAdminLayoutAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutUsersIndexRoute =
  LayoutAdminLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutSubmissionsIndexRoute =
  LayoutAdminLayoutSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutStationsIndexRoute =
  LayoutAdminLayoutStationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutLocationsIndexRoute =
  LayoutAdminLayoutLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutListsIndexRoute =
  LayoutAdminLayoutListsIndexRouteImport.update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutCommentsIndexRoute =
  LayoutAdminLayoutCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutUsersIdRoute =
  LayoutAdminLayoutUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutSubmissionsIdRoute =
  LayoutAdminLayoutSubmissionsIdRouteImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutStationsIdRoute =
  LayoutAdminLayoutStationsIdRouteImport.update({
    id: '/stations/$id',
    path: '/stations/$id',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)
const LayoutAdminLayoutLocationsIdRoute =
  LayoutAdminLayoutLocationsIdRouteImport.update({
    id: '/locations/$id',
    path: '/locations/$id',
    getParentRoute: () => LayoutAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/share-target': typeof ShareTargetRoute
  '/about': typeof LayoutAboutRoute
  '/analyzer': typeof LayoutAnalyzerRoute
  '/changelog': typeof LayoutChangelogRoute
  '/clf-export': typeof LayoutClfExportRoute
  '/contact': typeof LayoutContactRoute
  '/deleted-entries': typeof LayoutDeletedEntriesRoute
  '/lists': typeof LayoutListsRouteWithChildren
  '/preferences': typeof LayoutPreferencesRoute
  '/stations': typeof LayoutStationsRoute
  '/statistics': typeof LayoutStatisticsRoute
  '/submission': typeof LayoutSubmissionRoute
  '/tos': typeof LayoutTosRoute
  '/account/reset-password': typeof LayoutAccountResetPasswordRoute
  '/account/settings': typeof LayoutAccountSettingsRoute
  '/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/account/two-factor': typeof LayoutAccountTwoFactorRoute
  '/admin': typeof LayoutAdminLayoutRouteWithChildren
  '/lists/$uuid': typeof LayoutListsUuidRoute
  '/lists/': typeof LayoutListsIndexRoute
  '/admin/audit-logs': typeof LayoutAdminLayoutAuditLogsRoute
  '/admin/settings': typeof LayoutAdminLayoutSettingsRoute
  '/admin/uke-import': typeof LayoutAdminLayoutUkeImportRoute
  '/admin/uke-permits': typeof LayoutAdminLayoutUkePermitsRoute
  '/admin/locations/$id': typeof LayoutAdminLayoutLocationsIdRoute
  '/admin/stations/$id': typeof LayoutAdminLayoutStationsIdRoute
  '/admin/submissions/$id': typeof LayoutAdminLayoutSubmissionsIdRoute
  '/admin/users/$id': typeof LayoutAdminLayoutUsersIdRoute
  '/admin/comments/': typeof LayoutAdminLayoutCommentsIndexRoute
  '/admin/lists/': typeof LayoutAdminLayoutListsIndexRoute
  '/admin/locations/': typeof LayoutAdminLayoutLocationsIndexRoute
  '/admin/stations/': typeof LayoutAdminLayoutStationsIndexRoute
  '/admin/submissions/': typeof LayoutAdminLayoutSubmissionsIndexRoute
  '/admin/users/': typeof LayoutAdminLayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/share-target': typeof ShareTargetRoute
  '/about': typeof LayoutAboutRoute
  '/analyzer': typeof LayoutAnalyzerRoute
  '/changelog': typeof LayoutChangelogRoute
  '/clf-export': typeof LayoutClfExportRoute
  '/contact': typeof LayoutContactRoute
  '/deleted-entries': typeof LayoutDeletedEntriesRoute
  '/preferences': typeof LayoutPreferencesRoute
  '/stations': typeof LayoutStationsRoute
  '/statistics': typeof LayoutStatisticsRoute
  '/submission': typeof LayoutSubmissionRoute
  '/tos': typeof LayoutTosRoute
  '/': typeof LayoutIndexRoute
  '/account/reset-password': typeof LayoutAccountResetPasswordRoute
  '/account/settings': typeof LayoutAccountSettingsRoute
  '/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/account/two-factor': typeof LayoutAccountTwoFactorRoute
  '/admin': typeof LayoutAdminLayoutRouteWithChildren
  '/lists/$uuid': typeof LayoutListsUuidRoute
  '/lists': typeof LayoutListsIndexRoute
  '/admin/audit-logs': typeof LayoutAdminLayoutAuditLogsRoute
  '/admin/settings': typeof LayoutAdminLayoutSettingsRoute
  '/admin/uke-import': typeof LayoutAdminLayoutUkeImportRoute
  '/admin/uke-permits': typeof LayoutAdminLayoutUkePermitsRoute
  '/admin/locations/$id': typeof LayoutAdminLayoutLocationsIdRoute
  '/admin/stations/$id': typeof LayoutAdminLayoutStationsIdRoute
  '/admin/submissions/$id': typeof LayoutAdminLayoutSubmissionsIdRoute
  '/admin/users/$id': typeof LayoutAdminLayoutUsersIdRoute
  '/admin/comments': typeof LayoutAdminLayoutCommentsIndexRoute
  '/admin/lists': typeof LayoutAdminLayoutListsIndexRoute
  '/admin/locations': typeof LayoutAdminLayoutLocationsIndexRoute
  '/admin/stations': typeof LayoutAdminLayoutStationsIndexRoute
  '/admin/submissions': typeof LayoutAdminLayoutSubmissionsIndexRoute
  '/admin/users': typeof LayoutAdminLayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/share-target': typeof ShareTargetRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/analyzer': typeof LayoutAnalyzerRoute
  '/_layout/changelog': typeof LayoutChangelogRoute
  '/_layout/clf-export': typeof LayoutClfExportRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/deleted-entries': typeof LayoutDeletedEntriesRoute
  '/_layout/lists': typeof LayoutListsRouteWithChildren
  '/_layout/preferences': typeof LayoutPreferencesRoute
  '/_layout/stations': typeof LayoutStationsRoute
  '/_layout/statistics': typeof LayoutStatisticsRoute
  '/_layout/submission': typeof LayoutSubmissionRoute
  '/_layout/tos': typeof LayoutTosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account/reset-password': typeof LayoutAccountResetPasswordRoute
  '/_layout/account/settings': typeof LayoutAccountSettingsRoute
  '/_layout/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/_layout/account/two-factor': typeof LayoutAccountTwoFactorRoute
  '/_layout/admin/_layout': typeof LayoutAdminLayoutRouteWithChildren
  '/_layout/lists/$uuid': typeof LayoutListsUuidRoute
  '/_layout/lists/': typeof LayoutListsIndexRoute
  '/_layout/admin/_layout/audit-logs': typeof LayoutAdminLayoutAuditLogsRoute
  '/_layout/admin/_layout/settings': typeof LayoutAdminLayoutSettingsRoute
  '/_layout/admin/_layout/uke-import': typeof LayoutAdminLayoutUkeImportRoute
  '/_layout/admin/_layout/uke-permits': typeof LayoutAdminLayoutUkePermitsRoute
  '/_layout/admin/_layout/locations/$id': typeof LayoutAdminLayoutLocationsIdRoute
  '/_layout/admin/_layout/stations/$id': typeof LayoutAdminLayoutStationsIdRoute
  '/_layout/admin/_layout/submissions/$id': typeof LayoutAdminLayoutSubmissionsIdRoute
  '/_layout/admin/_layout/users/$id': typeof LayoutAdminLayoutUsersIdRoute
  '/_layout/admin/_layout/comments/': typeof LayoutAdminLayoutCommentsIndexRoute
  '/_layout/admin/_layout/lists/': typeof LayoutAdminLayoutListsIndexRoute
  '/_layout/admin/_layout/locations/': typeof LayoutAdminLayoutLocationsIndexRoute
  '/_layout/admin/_layout/stations/': typeof LayoutAdminLayoutStationsIndexRoute
  '/_layout/admin/_layout/submissions/': typeof LayoutAdminLayoutSubmissionsIndexRoute
  '/_layout/admin/_layout/users/': typeof LayoutAdminLayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share-target'
    | '/about'
    | '/analyzer'
    | '/changelog'
    | '/clf-export'
    | '/contact'
    | '/deleted-entries'
    | '/lists'
    | '/preferences'
    | '/stations'
    | '/statistics'
    | '/submission'
    | '/tos'
    | '/account/reset-password'
    | '/account/settings'
    | '/account/submissions'
    | '/account/two-factor'
    | '/admin'
    | '/lists/$uuid'
    | '/lists/'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/uke-import'
    | '/admin/uke-permits'
    | '/admin/locations/$id'
    | '/admin/stations/$id'
    | '/admin/submissions/$id'
    | '/admin/users/$id'
    | '/admin/comments/'
    | '/admin/lists/'
    | '/admin/locations/'
    | '/admin/stations/'
    | '/admin/submissions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/share-target'
    | '/about'
    | '/analyzer'
    | '/changelog'
    | '/clf-export'
    | '/contact'
    | '/deleted-entries'
    | '/preferences'
    | '/stations'
    | '/statistics'
    | '/submission'
    | '/tos'
    | '/'
    | '/account/reset-password'
    | '/account/settings'
    | '/account/submissions'
    | '/account/two-factor'
    | '/admin'
    | '/lists/$uuid'
    | '/lists'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/uke-import'
    | '/admin/uke-permits'
    | '/admin/locations/$id'
    | '/admin/stations/$id'
    | '/admin/submissions/$id'
    | '/admin/users/$id'
    | '/admin/comments'
    | '/admin/lists'
    | '/admin/locations'
    | '/admin/stations'
    | '/admin/submissions'
    | '/admin/users'
  id:
    | '__root__'
    | '/_layout'
    | '/share-target'
    | '/_layout/about'
    | '/_layout/analyzer'
    | '/_layout/changelog'
    | '/_layout/clf-export'
    | '/_layout/contact'
    | '/_layout/deleted-entries'
    | '/_layout/lists'
    | '/_layout/preferences'
    | '/_layout/stations'
    | '/_layout/statistics'
    | '/_layout/submission'
    | '/_layout/tos'
    | '/_layout/'
    | '/_layout/account/reset-password'
    | '/_layout/account/settings'
    | '/_layout/account/submissions'
    | '/_layout/account/two-factor'
    | '/_layout/admin/_layout'
    | '/_layout/lists/$uuid'
    | '/_layout/lists/'
    | '/_layout/admin/_layout/audit-logs'
    | '/_layout/admin/_layout/settings'
    | '/_layout/admin/_layout/uke-import'
    | '/_layout/admin/_layout/uke-permits'
    | '/_layout/admin/_layout/locations/$id'
    | '/_layout/admin/_layout/stations/$id'
    | '/_layout/admin/_layout/submissions/$id'
    | '/_layout/admin/_layout/users/$id'
    | '/_layout/admin/_layout/comments/'
    | '/_layout/admin/_layout/lists/'
    | '/_layout/admin/_layout/locations/'
    | '/_layout/admin/_layout/stations/'
    | '/_layout/admin/_layout/submissions/'
    | '/_layout/admin/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ShareTargetRoute: typeof ShareTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-target': {
      id: '/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof ShareTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tos': {
      id: '/_layout/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof LayoutTosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/submission': {
      id: '/_layout/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof LayoutSubmissionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/statistics': {
      id: '/_layout/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof LayoutStatisticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stations': {
      id: '/_layout/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof LayoutStationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/preferences': {
      id: '/_layout/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof LayoutPreferencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lists': {
      id: '/_layout/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof LayoutListsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/deleted-entries': {
      id: '/_layout/deleted-entries'
      path: '/deleted-entries'
      fullPath: '/deleted-entries'
      preLoaderRoute: typeof LayoutDeletedEntriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clf-export': {
      id: '/_layout/clf-export'
      path: '/clf-export'
      fullPath: '/clf-export'
      preLoaderRoute: typeof LayoutClfExportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/changelog': {
      id: '/_layout/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof LayoutChangelogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyzer': {
      id: '/_layout/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof LayoutAnalyzerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lists/': {
      id: '/_layout/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof LayoutListsIndexRouteImport
      parentRoute: typeof LayoutListsRoute
    }
    '/_layout/lists/$uuid': {
      id: '/_layout/lists/$uuid'
      path: '/$uuid'
      fullPath: '/lists/$uuid'
      preLoaderRoute: typeof LayoutListsUuidRouteImport
      parentRoute: typeof LayoutListsRoute
    }
    '/_layout/admin/_layout': {
      id: '/_layout/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/two-factor': {
      id: '/_layout/account/two-factor'
      path: '/account/two-factor'
      fullPath: '/account/two-factor'
      preLoaderRoute: typeof LayoutAccountTwoFactorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/submissions': {
      id: '/_layout/account/submissions'
      path: '/account/submissions'
      fullPath: '/account/submissions'
      preLoaderRoute: typeof LayoutAccountSubmissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/settings': {
      id: '/_layout/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof LayoutAccountSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/reset-password': {
      id: '/_layout/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof LayoutAccountResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/_layout/uke-permits': {
      id: '/_layout/admin/_layout/uke-permits'
      path: '/uke-permits'
      fullPath: '/admin/uke-permits'
      preLoaderRoute: typeof LayoutAdminLayoutUkePermitsRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/uke-import': {
      id: '/_layout/admin/_layout/uke-import'
      path: '/uke-import'
      fullPath: '/admin/uke-import'
      preLoaderRoute: typeof LayoutAdminLayoutUkeImportRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/settings': {
      id: '/_layout/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAdminLayoutSettingsRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/audit-logs': {
      id: '/_layout/admin/_layout/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof LayoutAdminLayoutAuditLogsRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/users/': {
      id: '/_layout/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof LayoutAdminLayoutUsersIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/submissions/': {
      id: '/_layout/admin/_layout/submissions/'
      path: '/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof LayoutAdminLayoutSubmissionsIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/stations/': {
      id: '/_layout/admin/_layout/stations/'
      path: '/stations'
      fullPath: '/admin/stations/'
      preLoaderRoute: typeof LayoutAdminLayoutStationsIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/locations/': {
      id: '/_layout/admin/_layout/locations/'
      path: '/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof LayoutAdminLayoutLocationsIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/lists/': {
      id: '/_layout/admin/_layout/lists/'
      path: '/lists'
      fullPath: '/admin/lists/'
      preLoaderRoute: typeof LayoutAdminLayoutListsIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/comments/': {
      id: '/_layout/admin/_layout/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof LayoutAdminLayoutCommentsIndexRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/users/$id': {
      id: '/_layout/admin/_layout/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof LayoutAdminLayoutUsersIdRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/submissions/$id': {
      id: '/_layout/admin/_layout/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/admin/submissions/$id'
      preLoaderRoute: typeof LayoutAdminLayoutSubmissionsIdRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/stations/$id': {
      id: '/_layout/admin/_layout/stations/$id'
      path: '/stations/$id'
      fullPath: '/admin/stations/$id'
      preLoaderRoute: typeof LayoutAdminLayoutStationsIdRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
    '/_layout/admin/_layout/locations/$id': {
      id: '/_layout/admin/_layout/locations/$id'
      path: '/locations/$id'
      fullPath: '/admin/locations/$id'
      preLoaderRoute: typeof LayoutAdminLayoutLocationsIdRouteImport
      parentRoute: typeof LayoutAdminLayoutRoute
    }
  }
}

interface LayoutListsRouteChildren {
  LayoutListsUuidRoute: typeof LayoutListsUuidRoute
  LayoutListsIndexRoute: typeof LayoutListsIndexRoute
}

const LayoutListsRouteChildren: LayoutListsRouteChildren = {
  LayoutListsUuidRoute: LayoutListsUuidRoute,
  LayoutListsIndexRoute: LayoutListsIndexRoute,
}

const LayoutListsRouteWithChildren = LayoutListsRoute._addFileChildren(
  LayoutListsRouteChildren,
)

interface LayoutAdminLayoutRouteChildren {
  LayoutAdminLayoutAuditLogsRoute: typeof LayoutAdminLayoutAuditLogsRoute
  LayoutAdminLayoutSettingsRoute: typeof LayoutAdminLayoutSettingsRoute
  LayoutAdminLayoutUkeImportRoute: typeof LayoutAdminLayoutUkeImportRoute
  LayoutAdminLayoutUkePermitsRoute: typeof LayoutAdminLayoutUkePermitsRoute
  LayoutAdminLayoutLocationsIdRoute: typeof LayoutAdminLayoutLocationsIdRoute
  LayoutAdminLayoutStationsIdRoute: typeof LayoutAdminLayoutStationsIdRoute
  LayoutAdminLayoutSubmissionsIdRoute: typeof LayoutAdminLayoutSubmissionsIdRoute
  LayoutAdminLayoutUsersIdRoute: typeof LayoutAdminLayoutUsersIdRoute
  LayoutAdminLayoutCommentsIndexRoute: typeof LayoutAdminLayoutCommentsIndexRoute
  LayoutAdminLayoutListsIndexRoute: typeof LayoutAdminLayoutListsIndexRoute
  LayoutAdminLayoutLocationsIndexRoute: typeof LayoutAdminLayoutLocationsIndexRoute
  LayoutAdminLayoutStationsIndexRoute: typeof LayoutAdminLayoutStationsIndexRoute
  LayoutAdminLayoutSubmissionsIndexRoute: typeof LayoutAdminLayoutSubmissionsIndexRoute
  LayoutAdminLayoutUsersIndexRoute: typeof LayoutAdminLayoutUsersIndexRoute
}

const LayoutAdminLayoutRouteChildren: LayoutAdminLayoutRouteChildren = {
  LayoutAdminLayoutAuditLogsRoute: LayoutAdminLayoutAuditLogsRoute,
  LayoutAdminLayoutSettingsRoute: LayoutAdminLayoutSettingsRoute,
  LayoutAdminLayoutUkeImportRoute: LayoutAdminLayoutUkeImportRoute,
  LayoutAdminLayoutUkePermitsRoute: LayoutAdminLayoutUkePermitsRoute,
  LayoutAdminLayoutLocationsIdRoute: LayoutAdminLayoutLocationsIdRoute,
  LayoutAdminLayoutStationsIdRoute: LayoutAdminLayoutStationsIdRoute,
  LayoutAdminLayoutSubmissionsIdRoute: LayoutAdminLayoutSubmissionsIdRoute,
  LayoutAdminLayoutUsersIdRoute: LayoutAdminLayoutUsersIdRoute,
  LayoutAdminLayoutCommentsIndexRoute: LayoutAdminLayoutCommentsIndexRoute,
  LayoutAdminLayoutListsIndexRoute: LayoutAdminLayoutListsIndexRoute,
  LayoutAdminLayoutLocationsIndexRoute: LayoutAdminLayoutLocationsIndexRoute,
  LayoutAdminLayoutStationsIndexRoute: LayoutAdminLayoutStationsIndexRoute,
  LayoutAdminLayoutSubmissionsIndexRoute:
    LayoutAdminLayoutSubmissionsIndexRoute,
  LayoutAdminLayoutUsersIndexRoute: LayoutAdminLayoutUsersIndexRoute,
}

const LayoutAdminLayoutRouteWithChildren =
  LayoutAdminLayoutRoute._addFileChildren(LayoutAdminLayoutRouteChildren)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutAnalyzerRoute: typeof LayoutAnalyzerRoute
  LayoutChangelogRoute: typeof LayoutChangelogRoute
  LayoutClfExportRoute: typeof LayoutClfExportRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutDeletedEntriesRoute: typeof LayoutDeletedEntriesRoute
  LayoutListsRoute: typeof LayoutListsRouteWithChildren
  LayoutPreferencesRoute: typeof LayoutPreferencesRoute
  LayoutStationsRoute: typeof LayoutStationsRoute
  LayoutStatisticsRoute: typeof LayoutStatisticsRoute
  LayoutSubmissionRoute: typeof LayoutSubmissionRoute
  LayoutTosRoute: typeof LayoutTosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountResetPasswordRoute: typeof LayoutAccountResetPasswordRoute
  LayoutAccountSettingsRoute: typeof LayoutAccountSettingsRoute
  LayoutAccountSubmissionsRoute: typeof LayoutAccountSubmissionsRoute
  LayoutAccountTwoFactorRoute: typeof LayoutAccountTwoFactorRoute
  LayoutAdminLayoutRoute: typeof LayoutAdminLayoutRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutAnalyzerRoute: LayoutAnalyzerRoute,
  LayoutChangelogRoute: LayoutChangelogRoute,
  LayoutClfExportRoute: LayoutClfExportRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutDeletedEntriesRoute: LayoutDeletedEntriesRoute,
  LayoutListsRoute: LayoutListsRouteWithChildren,
  LayoutPreferencesRoute: LayoutPreferencesRoute,
  LayoutStationsRoute: LayoutStationsRoute,
  LayoutStatisticsRoute: LayoutStatisticsRoute,
  LayoutSubmissionRoute: LayoutSubmissionRoute,
  LayoutTosRoute: LayoutTosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountResetPasswordRoute: LayoutAccountResetPasswordRoute,
  LayoutAccountSettingsRoute: LayoutAccountSettingsRoute,
  LayoutAccountSubmissionsRoute: LayoutAccountSubmissionsRoute,
  LayoutAccountTwoFactorRoute: LayoutAccountTwoFactorRoute,
  LayoutAdminLayoutRoute: LayoutAdminLayoutRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ShareTargetRoute: ShareTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
