/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSubmissionRouteImport } from './routes/_layout/submission'
import { Route as LayoutStationsRouteImport } from './routes/_layout/stations'
import { Route as LayoutPreferencesRouteImport } from './routes/_layout/preferences'
import { Route as LayoutClfExportRouteImport } from './routes/_layout/clf-export'
import { Route as LayoutAdminUkeImportRouteImport } from './routes/_layout/admin/uke-import'
import { Route as LayoutAdminSettingsRouteImport } from './routes/_layout/admin/settings'
import { Route as LayoutAdminLayoutRouteImport } from './routes/_layout/admin/_layout'
import { Route as LayoutAccountSubmissionsRouteImport } from './routes/_layout/account/submissions'
import { Route as LayoutAccountSettingsRouteImport } from './routes/_layout/account/settings'
import { Route as LayoutAdminUsersIndexRouteImport } from './routes/_layout/admin/users/index'
import { Route as LayoutAdminSubmissionsIndexRouteImport } from './routes/_layout/admin/submissions/index'
import { Route as LayoutAdminStationsIndexRouteImport } from './routes/_layout/admin/stations/index'
import { Route as LayoutAdminLocationsIndexRouteImport } from './routes/_layout/admin/locations/index'
import { Route as LayoutAdminUsersIdRouteImport } from './routes/_layout/admin/users/$id'
import { Route as LayoutAdminSubmissionsIdRouteImport } from './routes/_layout/admin/submissions/$id'
import { Route as LayoutAdminStationsIdRouteImport } from './routes/_layout/admin/stations/$id'
import { Route as LayoutAdminLocationsIdRouteImport } from './routes/_layout/admin/locations/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubmissionRoute = LayoutSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStationsRoute = LayoutStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPreferencesRoute = LayoutPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClfExportRoute = LayoutClfExportRouteImport.update({
  id: '/clf-export',
  path: '/clf-export',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUkeImportRoute = LayoutAdminUkeImportRouteImport.update({
  id: '/admin/uke-import',
  path: '/admin/uke-import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSettingsRoute = LayoutAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminLayoutRoute = LayoutAdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountSubmissionsRoute =
  LayoutAccountSubmissionsRouteImport.update({
    id: '/account/submissions',
    path: '/account/submissions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccountSettingsRoute = LayoutAccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersIndexRoute = LayoutAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSubmissionsIndexRoute =
  LayoutAdminSubmissionsIndexRouteImport.update({
    id: '/admin/submissions/',
    path: '/admin/submissions/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminStationsIndexRoute =
  LayoutAdminStationsIndexRouteImport.update({
    id: '/admin/stations/',
    path: '/admin/stations/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminLocationsIndexRoute =
  LayoutAdminLocationsIndexRouteImport.update({
    id: '/admin/locations/',
    path: '/admin/locations/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminUsersIdRoute = LayoutAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSubmissionsIdRoute =
  LayoutAdminSubmissionsIdRouteImport.update({
    id: '/admin/submissions/$id',
    path: '/admin/submissions/$id',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminStationsIdRoute = LayoutAdminStationsIdRouteImport.update({
  id: '/admin/stations/$id',
  path: '/admin/stations/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminLocationsIdRoute = LayoutAdminLocationsIdRouteImport.update({
  id: '/admin/locations/$id',
  path: '/admin/locations/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/clf-export': typeof LayoutClfExportRoute
  '/preferences': typeof LayoutPreferencesRoute
  '/stations': typeof LayoutStationsRoute
  '/submission': typeof LayoutSubmissionRoute
  '/account/settings': typeof LayoutAccountSettingsRoute
  '/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/admin': typeof LayoutAdminLayoutRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/admin/uke-import': typeof LayoutAdminUkeImportRoute
  '/admin/locations/$id': typeof LayoutAdminLocationsIdRoute
  '/admin/stations/$id': typeof LayoutAdminStationsIdRoute
  '/admin/submissions/$id': typeof LayoutAdminSubmissionsIdRoute
  '/admin/users/$id': typeof LayoutAdminUsersIdRoute
  '/admin/locations/': typeof LayoutAdminLocationsIndexRoute
  '/admin/stations/': typeof LayoutAdminStationsIndexRoute
  '/admin/submissions/': typeof LayoutAdminSubmissionsIndexRoute
  '/admin/users/': typeof LayoutAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clf-export': typeof LayoutClfExportRoute
  '/preferences': typeof LayoutPreferencesRoute
  '/stations': typeof LayoutStationsRoute
  '/submission': typeof LayoutSubmissionRoute
  '/': typeof LayoutIndexRoute
  '/account/settings': typeof LayoutAccountSettingsRoute
  '/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/admin': typeof LayoutAdminLayoutRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/admin/uke-import': typeof LayoutAdminUkeImportRoute
  '/admin/locations/$id': typeof LayoutAdminLocationsIdRoute
  '/admin/stations/$id': typeof LayoutAdminStationsIdRoute
  '/admin/submissions/$id': typeof LayoutAdminSubmissionsIdRoute
  '/admin/users/$id': typeof LayoutAdminUsersIdRoute
  '/admin/locations': typeof LayoutAdminLocationsIndexRoute
  '/admin/stations': typeof LayoutAdminStationsIndexRoute
  '/admin/submissions': typeof LayoutAdminSubmissionsIndexRoute
  '/admin/users': typeof LayoutAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/clf-export': typeof LayoutClfExportRoute
  '/_layout/preferences': typeof LayoutPreferencesRoute
  '/_layout/stations': typeof LayoutStationsRoute
  '/_layout/submission': typeof LayoutSubmissionRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account/settings': typeof LayoutAccountSettingsRoute
  '/_layout/account/submissions': typeof LayoutAccountSubmissionsRoute
  '/_layout/admin/_layout': typeof LayoutAdminLayoutRoute
  '/_layout/admin/settings': typeof LayoutAdminSettingsRoute
  '/_layout/admin/uke-import': typeof LayoutAdminUkeImportRoute
  '/_layout/admin/locations/$id': typeof LayoutAdminLocationsIdRoute
  '/_layout/admin/stations/$id': typeof LayoutAdminStationsIdRoute
  '/_layout/admin/submissions/$id': typeof LayoutAdminSubmissionsIdRoute
  '/_layout/admin/users/$id': typeof LayoutAdminUsersIdRoute
  '/_layout/admin/locations/': typeof LayoutAdminLocationsIndexRoute
  '/_layout/admin/stations/': typeof LayoutAdminStationsIndexRoute
  '/_layout/admin/submissions/': typeof LayoutAdminSubmissionsIndexRoute
  '/_layout/admin/users/': typeof LayoutAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clf-export'
    | '/preferences'
    | '/stations'
    | '/submission'
    | '/account/settings'
    | '/account/submissions'
    | '/admin'
    | '/admin/settings'
    | '/admin/uke-import'
    | '/admin/locations/$id'
    | '/admin/stations/$id'
    | '/admin/submissions/$id'
    | '/admin/users/$id'
    | '/admin/locations/'
    | '/admin/stations/'
    | '/admin/submissions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clf-export'
    | '/preferences'
    | '/stations'
    | '/submission'
    | '/'
    | '/account/settings'
    | '/account/submissions'
    | '/admin'
    | '/admin/settings'
    | '/admin/uke-import'
    | '/admin/locations/$id'
    | '/admin/stations/$id'
    | '/admin/submissions/$id'
    | '/admin/users/$id'
    | '/admin/locations'
    | '/admin/stations'
    | '/admin/submissions'
    | '/admin/users'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/clf-export'
    | '/_layout/preferences'
    | '/_layout/stations'
    | '/_layout/submission'
    | '/_layout/'
    | '/_layout/account/settings'
    | '/_layout/account/submissions'
    | '/_layout/admin/_layout'
    | '/_layout/admin/settings'
    | '/_layout/admin/uke-import'
    | '/_layout/admin/locations/$id'
    | '/_layout/admin/stations/$id'
    | '/_layout/admin/submissions/$id'
    | '/_layout/admin/users/$id'
    | '/_layout/admin/locations/'
    | '/_layout/admin/stations/'
    | '/_layout/admin/submissions/'
    | '/_layout/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/submission': {
      id: '/_layout/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof LayoutSubmissionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stations': {
      id: '/_layout/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof LayoutStationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/preferences': {
      id: '/_layout/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof LayoutPreferencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clf-export': {
      id: '/_layout/clf-export'
      path: '/clf-export'
      fullPath: '/clf-export'
      preLoaderRoute: typeof LayoutClfExportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/uke-import': {
      id: '/_layout/admin/uke-import'
      path: '/admin/uke-import'
      fullPath: '/admin/uke-import'
      preLoaderRoute: typeof LayoutAdminUkeImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/settings': {
      id: '/_layout/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAdminSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/_layout': {
      id: '/_layout/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/submissions': {
      id: '/_layout/account/submissions'
      path: '/account/submissions'
      fullPath: '/account/submissions'
      preLoaderRoute: typeof LayoutAccountSubmissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/settings': {
      id: '/_layout/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof LayoutAccountSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users/': {
      id: '/_layout/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof LayoutAdminUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/submissions/': {
      id: '/_layout/admin/submissions/'
      path: '/admin/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof LayoutAdminSubmissionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/stations/': {
      id: '/_layout/admin/stations/'
      path: '/admin/stations'
      fullPath: '/admin/stations/'
      preLoaderRoute: typeof LayoutAdminStationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/locations/': {
      id: '/_layout/admin/locations/'
      path: '/admin/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof LayoutAdminLocationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users/$id': {
      id: '/_layout/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof LayoutAdminUsersIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/submissions/$id': {
      id: '/_layout/admin/submissions/$id'
      path: '/admin/submissions/$id'
      fullPath: '/admin/submissions/$id'
      preLoaderRoute: typeof LayoutAdminSubmissionsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/stations/$id': {
      id: '/_layout/admin/stations/$id'
      path: '/admin/stations/$id'
      fullPath: '/admin/stations/$id'
      preLoaderRoute: typeof LayoutAdminStationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/locations/$id': {
      id: '/_layout/admin/locations/$id'
      path: '/admin/locations/$id'
      fullPath: '/admin/locations/$id'
      preLoaderRoute: typeof LayoutAdminLocationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutClfExportRoute: typeof LayoutClfExportRoute
  LayoutPreferencesRoute: typeof LayoutPreferencesRoute
  LayoutStationsRoute: typeof LayoutStationsRoute
  LayoutSubmissionRoute: typeof LayoutSubmissionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountSettingsRoute: typeof LayoutAccountSettingsRoute
  LayoutAccountSubmissionsRoute: typeof LayoutAccountSubmissionsRoute
  LayoutAdminLayoutRoute: typeof LayoutAdminLayoutRoute
  LayoutAdminSettingsRoute: typeof LayoutAdminSettingsRoute
  LayoutAdminUkeImportRoute: typeof LayoutAdminUkeImportRoute
  LayoutAdminLocationsIdRoute: typeof LayoutAdminLocationsIdRoute
  LayoutAdminStationsIdRoute: typeof LayoutAdminStationsIdRoute
  LayoutAdminSubmissionsIdRoute: typeof LayoutAdminSubmissionsIdRoute
  LayoutAdminUsersIdRoute: typeof LayoutAdminUsersIdRoute
  LayoutAdminLocationsIndexRoute: typeof LayoutAdminLocationsIndexRoute
  LayoutAdminStationsIndexRoute: typeof LayoutAdminStationsIndexRoute
  LayoutAdminSubmissionsIndexRoute: typeof LayoutAdminSubmissionsIndexRoute
  LayoutAdminUsersIndexRoute: typeof LayoutAdminUsersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClfExportRoute: LayoutClfExportRoute,
  LayoutPreferencesRoute: LayoutPreferencesRoute,
  LayoutStationsRoute: LayoutStationsRoute,
  LayoutSubmissionRoute: LayoutSubmissionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountSettingsRoute: LayoutAccountSettingsRoute,
  LayoutAccountSubmissionsRoute: LayoutAccountSubmissionsRoute,
  LayoutAdminLayoutRoute: LayoutAdminLayoutRoute,
  LayoutAdminSettingsRoute: LayoutAdminSettingsRoute,
  LayoutAdminUkeImportRoute: LayoutAdminUkeImportRoute,
  LayoutAdminLocationsIdRoute: LayoutAdminLocationsIdRoute,
  LayoutAdminStationsIdRoute: LayoutAdminStationsIdRoute,
  LayoutAdminSubmissionsIdRoute: LayoutAdminSubmissionsIdRoute,
  LayoutAdminUsersIdRoute: LayoutAdminUsersIdRoute,
  LayoutAdminLocationsIndexRoute: LayoutAdminLocationsIndexRoute,
  LayoutAdminStationsIndexRoute: LayoutAdminStationsIndexRoute,
  LayoutAdminSubmissionsIndexRoute: LayoutAdminSubmissionsIndexRoute,
  LayoutAdminUsersIndexRoute: LayoutAdminUsersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
